### ISSUE TITLE
IP Addresses are not correctly relayed on DigitalOcean

### ISSUE THREAD

**Issue by komninoschatzipapas** [mixpanel/tracking-proxy#31]
We have deployed this proxy on a DigitalOcean app as follows (using the one-click install on the Readme of this project):
```
ingress:
  rules:
  - component:
      name: mixpanel-api-proxy
    match:
      path:
        prefix: /api/t
services:
- dockerfile_path: ./Dockerfile
  git:
    branch: master
    repo_clone_url: https://github.com/mixpanel/tracking-proxy.git
  http_port: 80
  instance_count: 1
  instance_size_slug: apps-s-1vcpu-1gb
  name: mixpanel-api-proxy
```

Unfortunately, our events on Mixpanel now show with Country and City as `(not set)`. We have double checked to ensure IP tracking is enabled on our Mixpanel.js setup.

If this helps, we know that DigitalOcean sends the end user's IP as the `do-connecting-ip` header on requests through the App platform.
